##########################################
##              ESP8266                 ##
##  |RS|          |#|     | 1|          ##
##  |A0| ADC      |#|     | 3|          ##
##  |16| LED      |#|     | 5| opto     ##
##  |14| cf1 8012 |#|     | 4| Реле     ##
##  |12| cf  8012 |#|     | 0| Кнопка   ##
##  |13| Внешняя  |#|     | 2|          ##
##  |15| SEL 8012 |#|     |GN|          ## 
##  |3V|          |#|     |5V|          ##
##########################################

substitutions:
  name: "ujin-connect-in"
  device_description: "реле"
esphome:
  name: $name

esp8266:
  board: esp_wroom_02

#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
# обязательные пакеты
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml


#-------------------------------------------
# GLOBAL 
#-----------------------------------------
globals:
  - id: cicle 
    type: int
    restore_value: no
    initial_value: '0'

#-------------------------------------------
# SWITCH
#-------------------------------------------
switch:
  - platform: gpio
    name: "Реле"
    pin: GPIO4
    id: relay
    on_turn_on:
      - light.turn_on:
          id: led_relay
    on_turn_off:
      - light.turn_off:
          id: led_relay
  - platform: template
    id: virtual_switch
    optimistic: true
    on_turn_on:
       then:
          - while:
              condition:
                binary_sensor.is_on: zero
              then:
                - delay: 0.0005s
                - lambda: |-
                    id(cicle) =  id(cicle)+1;
          - switch.turn_on: relay
          - logger.log:
              format: "Задержка вкл: (%d)"
              args: "id(cicle)"
          - lambda: |- 
              id(cicle) = 0;
    on_turn_off:
       then:
          - while:
              condition:
                binary_sensor.is_on: zero
              then:
                - delay: 0.0005s
                - lambda: |-
                    id(cicle) =  id(cicle)+1;
          - switch.turn_off: relay
          - logger.log:
              format: "Задержка выкл: (%d)"
              args: "id(cicle)"
          - lambda: |- 
              id(cicle) = 0;
#-------------------------------------------
# OUTPUT
#-------------------------------------------
output:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: true
    id: gpio_16

#-------------------------------------------
# LIGHT
#-------------------------------------------
light:
  - platform: binary
    output: gpio_16   
    id: led_relay

#-------------------------------------------
# BINARY_SENSOR
#-------------------------------------------
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: true
      allow_other_uses: true
    update_interval: 0.0005s
    id: zero
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "button"
    on_press:    
      - switch.toggle: virtual_switch
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    name: "external button" 
    on_press:    
      - switch.toggle: virtual_switch
#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  - platform: adc
    name: ADC
    pin: A0
    update_interval: 30s
    
  - platform: hlw8012
    current_resistor:  0.001
    voltage_divider: 2520
    model: hlw8012
    sel_pin: 
      number: GPIO15
    cf_pin: GPIO12
    cf1_pin: GPIO14
    current:
      name: "Current"
      accuracy_decimals: 2
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
    power:
      name: "Power"
      accuracy_decimals: 2
    energy:
      name: "Energy"
      accuracy_decimals: 2
    update_interval: 5s

  - platform: pulse_counter
    name: "Frequency"
    icon: 'mdi:pulse'
    pin: 
      number: GPIO5
      mode:
        input: true
      allow_other_uses: true
    unit_of_measurement: 'Hz'
    update_interval: 5s
    accuracy_decimals: 0
    filters:
      - multiply: 0.0054

