#-------------------------------------------
# Add yaml 
#packages:
#  2in: !include 
#    file: packages/ujin/2in.yaml
#    vars:
#      one_pin: GPIO33
#      two_pin: GPIO3
# and copy file esphome/packages/ujin

#-------------------------------------------
# BINARY SENSOR
#-------------------------------------------
binary_sensor:
  - platform: gpio
    pin:
      number: $one_pin
      inverted: true
    id: "input1"
    name: "Вход 1"
    icon: mdi:inbox-arrow-down-outline
    on_press:
      then:
        - lambda: |-
            int8_t act_in1 = id(g_in1);
            switch(act_in1) {
              case 0: break;  // Не использовать
              case 1: id(light_dimmer1).turn_on().perform(); break;  // Стандартный: включение по нажатию
              case 2: id(light_dimmer1).toggle().perform(); break;  // Проходной: переключение по нажатию
              case 3: id(light_dimmer1).turn_on().perform(); break;  // Без фиксации замыкающий: включение по нажатию
              case 4: id(light_dimmer1).turn_off().perform(); break; // Без фиксации размыкающий: выключение по нажатию
            }
    on_release: 
      then:
        - lambda: |-
            int8_t act_in1 = id(g_in1);
            switch(act_in1) {
              case 0: break;  // Не использовать
              case 1: id(light_dimmer1).turn_off().perform(); break;  // Стандартный: выключение по отпусканию
              case 2: break;  // Проходной: ничего по отпусканию
              case 3: id(light_dimmer1).turn_off().perform(); break;  // Без фиксации замыкающий: выключение по отпусканию
              case 4: id(light_dimmer1).turn_on().perform(); break;   // Без фиксации размыкающий: включение по отпусканию
            }

  - platform: gpio
    pin:
      number: $two_pin
      inverted: true
    id: "input2"
    name: "Вход 2"       
    icon: mdi:inbox-arrow-down-outline
    on_press:
      then:
        - lambda: |-
            int8_t act_in2 = id(g_in2);
            switch(act_in2) {
              case 0: break;
              case 1: id(light_dimmer2).turn_on().perform(); break;
              case 2: id(light_dimmer2).toggle().perform(); break;
              case 3: id(light_dimmer2).turn_on().perform(); break;
              case 4: id(light_dimmer2).turn_off().perform(); break;
            }
    on_release: 
      then:
        - lambda: |-
            int8_t act_in2 = id(g_in2);
            switch(act_in2) {
              case 0: break;
              case 1: id(light_dimmer2).turn_off().perform(); break;
              case 2: break;
              case 3: id(light_dimmer2).turn_off().perform(); break;
              case 4: id(light_dimmer2).turn_on().perform(); break;
            }

#-------------------------------------------
# SELECT
#-------------------------------------------
select:
  - platform: template
    name: "Тип внешнего выключателя 1"
    entity_category: config
    id: type_external_1
    icon: mdi:dip-switch
    options:
      - "Не использовать"              
      - "Стандартный"             
      - "Проходной"
      - "Без фиксации замыкающий"             
      - "Без фиксации размыкающий"                
    initial_option: "Не использовать"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            std::string option = x;
            if (option == "Не использовать") id(g_in1) = 0;
            else if (option == "Стандартный") id(g_in1) = 1;
            else if (option == "Проходной") id(g_in1) = 2;
            else if (option == "Без фиксации замыкающий") id(g_in1) = 3;
            else if (option == "Без фиксации размыкающий") id(g_in1) = 4;
        - logger.log:
            format: "IN1 option: %s (%d)"
            args: ["x.c_str()", "id(g_in1)"]

  - platform: template
    name: "Тип внешнего выключателя 2"
    entity_category: config
    id: type_external_2
    icon: mdi:dip-switch
    options:
      - "Не использовать"              
      - "Стандартный"             
      - "Проходной"
      - "Без фиксации замыкающий"             
      - "Без фиксации размыкающий"                
    initial_option: "Не использовать"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            std::string option = x;
            if (option == "Не использовать") id(g_in2) = 0;
            else if (option == "Стандартный") id(g_in2) = 1;
            else if (option == "Проходной") id(g_in2) = 2;
            else if (option == "Без фиксации замыкающий") id(g_in2) = 3;
            else if (option == "Без фиксации размыкающий") id(g_in2) = 4;
        - logger.log:
            format: "IN2 option: %s (%d)"
            args: ["x.c_str()", "id(g_in2)"]

#-------------------------------------------
# GLOBALS
#-------------------------------------------            
globals:
  - id: g_in1
    type: int
    restore_value: true
    initial_value: '0'

  - id: g_in2
    type: int
    restore_value: true
    initial_value: '0'