substitutions:
  name: ujin-heat-display
  device_description: Ujin heat display
  room: kithen

esphome:
  name: "${name}"
  friendly_name: ujin-heat-display
  comment: "${device_description}"
  on_boot:
    - rtttl.play: 'short:d=20,o=5,b=100:e6' 

esp32:
  board: denky_d4
  flash_size: 8MB
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1" 
      
#-------------------------------------------
# Logger #32 356 байт
#-------------------------------------------
#logger: 
#  hardware_uart: UART0
  
#-------------------------------------------
# I2c
#-------------------------------------------
i2c:
  sda: GPIO13 #15
  scl: GPIO15 # 13
  scan: true


#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
# обязательные пакеты
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml

# Кнопки
  button: !include 
    file: packages/ujin/button/button_adc.yaml
    vars:
      button_pin: 36 # 8 #

# Zigbee шлюз      
  zigbee: !include 
    file: packages/ujin/zigbee.yaml
    vars:
      TX_Z: GPIO14
      RX_Z: GPIO3

# Датчики  
# Датчик освещености
  ltr: !include 
    file: packages/ujin/sensor/LTR329.yaml

# Датчик температуры встроенный NTC
  ntc_i: !include 
    file: packages/ujin/sensor/ntc_internal.yaml
    vars:
      ntc_internal_pin: 39

# Датчик температуры внешний NTC
  ntc_e: !include 
    file: packages/ujin/sensor/ntc_external.yaml
    vars:
      ntc_external_pin: 35
      rezerv_temp: bme680_t

# Датчик температуры, влажности, CO2, давления, VOC, качества воздуха 
  bme680_bsec: !include 
    file: packages/ujin/sensor/bme680_bsec2.yaml
    vars:
      id_bme680_t: bme680_t
      id_bme680_h: bme680_h
      id_bme680_p: bme680_p
      id_bme680_iaq: bme680_iaq
      id_bme680_co2: bme680_co2
      id_bme680_voc: bme680_voc
      model_bme: bme688
      address_bme680: 0x76
      t_offset: 0

# Дисплей
  display: !include packages/ujin/display/display.yaml

  thermostat: !include  packages/ujin/display/thermostat.yaml
  humm: !include packages/ujin/display/humm.yaml
  barometr: !include packages/ujin/display/barometr_page.yaml
  #barometr: !include  packages/ujin/display/barometr.yaml
  co2: !include packages/ujin/display/co2.yaml
  iaq: !include packages/ujin/display/iaq.yaml
  voc: !include packages/ujin/display/voc.yaml

  clock: !include packages/ujin/display/clock_page.yaml
  dishwasher: !include 
    file: packages/ujin/display/dishwasher.yaml
    vars:
      sensor_dishwasher_percent: sensor.siemens_dishwasher_program_progress
      sensor_dishwasher_time: sensor.siemens_dishwasher_remaining_program_time  
      sensor_dishwasher_program_phase: sensor.siemens_dishwasher_program_phase
      binary_sensor_dishwasher_door: binary_sensor.siemens_dishwasher_door
      switch_dishwasher_power: switch.siemens_dishwasher_power

#-------------------------------------------
# SWITCH
#-------------------------------------------
switch:
  - platform: template
    name: "Звук нажатие клавиш"
    optimistic: True
    id: sound
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:volume-off

#-------------------------------------------
# Outputs
#-------------------------------------------
output:
  - platform: ledc
    pin: GPIO12
    id: rtttl_out

#-------------------------------------------
# RTTTL
#-------------------------------------------
rtttl:
  output: rtttl_out
  gain: 60%

#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
# sensor sound_leve
  - platform: sound_level
    passive: false
    peak:
      name: "шум пиковый уровень"
      id: Leq_id
      icon: mdi:waveform
   #   filters:
    #    - delta: 5


  - platform: adc
    pin: 32
    name: adc_32
    id: adc_32
    attenuation: auto
    update_interval: 5s

  - platform: resistance
    sensor: adc_32
    configuration: UPSTREAM
    resistor: 100 kOhm
    name: resistor_32 

#-------------------------------------------
# I2S
#-------------------------------------------
i2s_audio:
  i2s_lrclk_pin: 
    number: 7
    ignore_pin_validation_error: true
  i2s_bclk_pin:  
    number: 20

#-------------------------------------------
# MICROPHONE
#-------------------------------------------
microphone:
  - platform: i2s_audio
    id: external_mic
    adc_type: external
    i2s_din_pin:     
      number: 8
      ignore_pin_validation_error: true
    channel: stereo
    pdm: false
    bits_per_sample: 16bit
    bits_per_channel: 8bit
    sample_rate: 16000
    







