#############################################################################
#----Страничка барометра-----------------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/ujin/display
#packages:
#  barometr: !include file: packages/ujin/display/barometr_page.yaml 
# 
#############################################################################

#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/barometr.jpg"
    id: barometr_image
    resize: 240x240
    type: RGB565

#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  - id: !extend bme_bsec2
    pressure:
      on_value:
        - lvgl.indicator.update:
            id: barometr_hand
            value: !lambda |- 
              return x;
        - lvgl.indicator.update:
            id: barometr_hand_z
            value: !lambda |- 
              return x;   
    temperature:
      on_value:
        - lvgl.indicator.update:
            id: temperatura_hand
            value: !lambda |- 
              return x;
################################################################

  - platform: template # Pressure 1h
    name: "${name} pressure old 1h"
    id: pressure_1h
    update_interval: never
    device_class: pressure
    disabled_by_default: true

  - platform: template # Pressure 2h
    name: "${name} pressure old 2h"
    id: pressure_2h
    update_interval: never
    device_class: pressure
    disabled_by_default: true

  - platform: template # Pressure 3h
    name: "${name} pressure old 3h"
    id: pressure_3h
    update_interval: never
    device_class: pressure
    disabled_by_default: true
    on_value:
      - lvgl.indicator.update:
          id: barometr_hand_3h
          value: !lambda |- 
            return x;
      - lvgl.indicator.update:
          id: barometr_hand_3hz
          value: !lambda |- 
            return x;

#-------------------------------------------
# SCRIPT
#-------------------------------------------
script:
  - id: time_sync_barometr
    then:
      - delay: 4s
      - lambda: !lambda |-
          id(pressure_3h).publish_state(id(bme680_p).state);
          id(pressure_2h).publish_state(id(bme680_p).state);
          id(pressure_1h).publish_state(id(bme680_p).state);
        
  - id: time_update_barometr
    then:
      lambda: !lambda |-
        id(pressure_3h).publish_state(id(pressure_2h).state);
        id(pressure_2h).publish_state(id(pressure_1h).state);
        id(pressure_1h).publish_state(id(bme680_p).state);
      
#-------------------------------------------
# TIME
#-------------------------------------------
time:
  - id: !extend sntp_time
    on_time_sync:
      - script.execute: time_sync_barometr
 #  on_time:
 #     - hours: '*'
  #      minutes: 50
  #      seconds: 0
  #      then:
  #        - script.execute: time_update_barometr
        

#-------------------------------------------
# INTERVAL
#-------------------------------------------
interval:    
  - interval: 1h
    then:
      - script.execute: time_update_barometr              
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Выводим на экран    
    - id: barometr_page    
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      scrollbar_mode: "OFF"
      widgets:
        - image:
            align: CENTER
            src: barometr_image
        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 480
            height: 480
            align: CENTER
            scrollbar_mode: "OFF"
            scrollable: false
            widgets:
            #######################
              - meter:
                  border_side: none
                  height: 240
                  width: 240
                  align: CENTER
                  bg_opa: TRANSP
                  text_color: 0xFFFFFF
                  scales:
# old pressure
                    - indicators:
                        - line:
                            id: barometr_hand_3h
                            width: 3
                            color: 0xE0E0E0 #white
                            r_mod: -15
                      rotation: 120
                      angle_range: 300 # Угол между началом и концом
                      range_from: 920 # Минимальное значение 920
                      range_to: 1080  # Максимальное значение 1080
                      ticks: 
                        count: 0 
# old pressure Z
                    - indicators:
                        - line:
                            id: barometr_hand_3hz
                            width: 7
                            color: 0xE0E0E0 #white
                            r_mod: -70
                      rotation: 300
                      angle_range: 300 # Угол между началом и концом
                      range_from: 920 # 690 # Минимальное значение
                      range_to: 1080 #810    
                      ticks: 
                        count: 0
# pressure
                    - indicators:
                        - line:
                            id: barometr_hand
                            width: 3
                            color: 0xFF0000 # red 0xE0E0E0 #white
                            r_mod: -15
                      rotation: 120
                      angle_range: 300 # Угол между началом и концом
                      range_from: 920 #690 # Минимальное значение
                      range_to: 1080 #810  # Максимальное значение
                      ticks: 
                        count: 0 
# pressure Z
                    - indicators:
                        - line:
                            id: barometr_hand_z
                            width: 7
                            color: 0xFF0000 # red 0xE0E0E0 #white
                            r_mod: -70
                      rotation: 300
                      angle_range: 300 # Угол между началом и концом
                      range_from: 920 #690 # Минимальное значение
                      range_to: 1080 #810 
                      ticks: 
                        count: 0
# temperatura
              - meter:
                  border_side: none
                  height: 50
                  width: 50
                  y: 90
                  align: CENTER
                  bg_opa: TRANSP
                  text_color: 0xFFFFFF
                  scales:
                    - indicators:
                        - line:
                            id: temperatura_hand
                            width: 3
                            color: 0xFF0000 # red 0xE0E0E0 #white
                            r_mod: 30
                      rotation: 180
                      angle_range: 180 # Угол между началом и концом
                      range_from: -10 # Минимальное значение
                      range_to: 50  # Максимальное значение
                      ticks: 
                        count: 0 
# CENTER
              - led:
                  align: CENTER
                  color: 0xFF0000
                  width: 15
                  height: 15