#############################################################################
#----Страничка  кнопока-----------------------------------------------------
#############################################################################
#  button: !include
#    file: packages/ujin/display/button_relay.yaml
#    vars:
#      button4_icon_0_0: "\U000F07AA" 

#############
#           #         
#           #  
#   0_0     #   
#           #      
#############


font:
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: button_65
    size: 65
    bpp: 4
    glyphs: [
      $button_icon_0_0
      ]   
   


#-------------------------------------------
# BINARY_SENSOR
#-------------------------------------------            
binary_sensor:
  - id: !extend bin_vl
    on_click:
      then:
        - light.turn_on: backlight
        - lvgl.page.show: button_page 
        - light.toggle: light_relay_1

  - id: !extend bin_nl
    on_click:
      then:
        - light.turn_on: backlight
        - lvgl.page.show: button_page 
        - light.toggle: light_relay_1
   
#-------------------------------------------
# OUTPUT
#-------------------------------------------      
output:
  - platform: gpio
    pin: 27
    id: 'relay_1'

#-------------------------------------------
# LIGHT
#-------------------------------------------
light:
  - platform: binary
    output: relay_1
    name: "1 лампа"
    id: light_relay_1
    restore_mode: ALWAYS_OFF
    icon: mdi:numeric-1-circle-outline    
    on_turn_on:
      lvgl.widget.update:
        id: w_button_0_0
        text_color: 0xFFFF00
    on_turn_off:
      lvgl.widget.update:
        id: w_button_0_0
        text_color: 0xB6B6B6
        
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
    - id: button_page     
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      widgets:

        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 240
            height: 240
            align: TOP_LEFT
            x: 0
            y: 0
            layout:
              pad_row: 10
              pad_column: 10
              type: GRID
              grid_columns: [FR(1)]
              grid_rows: [FR(1)]
            widgets:
            ########################
              - button:
               #   checkable: $button_checkable_0_0
                  id: b_button_0_0
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button_65
                        align: center
                        text: $button_icon_0_0
                        id: w_button_0_0


  