#############################################################################
#----Страничка 4 кнопоки улица-----------------------------------------------------
#############################################################################
#  button: !include
#    file: packages/ujin/display/button-4.yaml
#    vars:
#      button4_icon_0_0: "\U000F116A" # gate-open
#      button4_entity_0_0: switch.sonoff_1000fd870d_1
#      button4_action_0_0: "script.vorota"
#      button4_checkable_0_0: "true"

#      button4_icon_0_1: "\U000F1169" # gate-arrow-right
#      button4_entity_0_1: switch.sonoff_1000fd870d_2
#      button4_action_0_1: "script.vorota_1_2"
#      button4_checkable_0_1: "true"

#      button4_icon_1_0: "\U000F0299" # gate
#      button4_entity_1_0: switch.sonoff_1000fd870d_3
#      button4_action_1_0: "script.vorota"
#      button4_checkable_1_0: "true"

#      button4_icon_1_1: "\U000F07AE" # cctv
#      button4_entity_1_1: light.cam
#      button4_action_1_1: "light.toggle"
#      button4_checkable_1_1: "true"



#########################
#           #           #
#           #           #
#   0_0     #   0_1     #
#           #           #
#########################
#           #           #
#           #           #
#   1_0     #   1_1     #
#           #           #
#########################

font:
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: button4_65
    size: 65
    bpp: 4
    glyphs: [
      $button4_icon_0_0,
      $button4_icon_0_1,
      $button4_icon_1_0,
      $button4_icon_1_1
      ]   
      
#-------------------------------------------
# Binary sensor
#-------------------------------------------
binary_sensor:
#-------------------------------------------
# 0 Ряд
#-------------------------------------------
#action:
 # - service: homeassistant.update_entity
 #   target:
 #     entity_id: switch.sonoff_1000xxxxxx

  - platform: homeassistant
    name: bin_button4_icon_0_0
    entity_id: $button4_entity_0_0
    trigger_on_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button4_0_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button4_0_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button4_0_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button4_icon_0_1
    entity_id: $button4_entity_0_1
    trigger_on_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button4_0_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button4_0_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button4_0_1
        text_color: 0xB6B6B6


          
#-------------------------------------------
# 1 Ряд
#-------------------------------------------
  - platform: homeassistant
    name: bin_button4_icon_1_0
    entity_id: $button4_entity_1_0
    trigger_on_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button4_1_0
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button4_1_0
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button4_1_0
        text_color: 0xB6B6B6
####################################
  - platform: homeassistant
    name: bin_button4_icon_1_1
    entity_id: $button4_entity_1_1
    trigger_on_initial_state: true
    #internal: true
    on_state:
      then:
        lvgl.widget.update:
          id: b_button4_1_1
          state:
            checked: !lambda return x;
    on_press:
      lvgl.widget.update:
        id: w_button4_1_1
        text_color: 0xFFFF00
    on_release:
      lvgl.widget.update:
        id: w_button4_1_1
        text_color: 0xB6B6B6
####################################




#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
    - id: button4_page     
      width: 100%
      bg_color: 0x000000
      bg_opa: cover
      widgets:

        - obj:
            bg_opa: TRANSP
            border_opa: TRANSP
            width: 240
            height: 240
            align: TOP_LEFT
            x: 0
            y: 0
            layout:
              pad_row: 10
              pad_column: 10
              type: GRID
              grid_columns: [FR(1), FR(1)]
              grid_rows: [FR(1), FR(1)]
            widgets:
            ########################
              - button:
                  checkable: $button4_checkable_0_0
                  id: b_button4_0_0
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button4_65
                        align: center
                        text: $button4_icon_0_0
                        id: w_button4_0_0
                  on_click:
                    - homeassistant.action:
                        action: $button4_action_0_0
                        data:
                          entity_id: $button4_entity_0_0

              - button:
                  checkable: $button4_checkable_0_1
                  id: b_button4_0_1
                  grid_cell_row_pos: 0 #Позиция ряд
                  grid_cell_column_pos: 1 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button4_65
                        align: center
                        text: $button4_icon_0_1
                        id: w_button4_0_1
                  on_click:
                    - homeassistant.action:
                        action: $button4_action_0_1
                        data:
                          entity_id: $button4_entity_0_1
            
            ########################
              - button:
                  checkable: $button4_checkable_1_0
                  id: b_button4_1_0
                  grid_cell_row_pos: 1 #Позиция ряд
                  grid_cell_column_pos: 0 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button4_65
                        align: center
                        text: $button4_icon_1_0
                        id: w_button4_1_0
                  on_click:
                    - homeassistant.action:
                        action: $button4_action_1_0
                        data:
                          entity_id: $button4_entity_1_0

              - button:
                  checkable: $button4_checkable_1_1
                  id: b_button4_1_1
                  grid_cell_row_pos: 1 #Позиция ряд
                  grid_cell_column_pos: 1 #Позиция колонка
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  grid_cell_row_span: 1 #Занять ячеек в ряде
                  grid_cell_column_span: 1 #Занять ячеек в колонке
                  bg_opa: 35%
                  widgets:
                    - label:
                        text_font: button4_65
                        align: center
                        text: $button4_icon_1_1
                        id: w_button4_1_1
                  on_click:
                    - homeassistant.action:
                        action: $button4_action_1_1
                        data:
                          entity_id: $button4_entity_1_1