#############################################################################
#----Страничка часов-----------------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/ujin/display
#packages:
#    file: packages/ujin/display/clock_page.yaml
#############################################################################

substitutions:
  characters: " !#%'()+=,-_.:³°/μ0123456789АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧЩШЬЫЪЭЮЯABCDEFGHIJKLMNOPQRSTUVWXYZабвгдеёжзийклмнопрстуфхцчшщьыъэюяabcdefghijklmnopqrstuvwxyz"
  number_characters: " :.-0123456789"
#-------------------------------------------
# FONT
#-------------------------------------------
font:
  - file: "font/DSEG7ModernMini-Bold.ttf"
    id: SEG50
    glyphs: ${number_characters}
    size: 50
    bpp: 4  
  - file: "gfonts://Roboto"
    id: roboto16
    glyphs: ${characters}
    size: 16
    bpp: 4  
    
#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/clok.jpg"
    id: clok_image
    resize: 240x240
    type: RGB565 


#-------------------------------------------
# SCRIPT
#------------------------------------------- 
script:
  - id: time_update_clock
    then:
      - lvgl.indicator.update:
          id: minute_hand
          value: !lambda |-
            return id(sntp_time).now().minute;
      - lvgl.indicator.update:
          id: minute_hand_b
          value: !lambda |-
            return id(sntp_time).now().minute;
      - lvgl.indicator.update:
          id: hour_hand
          value: !lambda |-
            auto now = id(sntp_time).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;
      - lvgl.indicator.update:
          id: hour_hand_b
          value: !lambda |-
            auto now = id(sntp_time).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;
      - lvgl.label.update:
          id: date_label
          text: !lambda |-
            static const char * const mon_names[] = { "ЯНВ", "ФЕВ", "МАР", "АПР", "МАЯ", "ИЮН", "ИЮЛ", "АВГ", "СЕН", "ОКТ", "НОЯ", "ДЕК"};
            static char date_buf[16];
            auto now = id(sntp_time).now();
            snprintf(date_buf, sizeof(date_buf), "%2d %s", now.day_of_month, mon_names[now.month-1]);
            return date_buf;
      - lvgl.label.update:
          id: day_label
          text: !lambda |-
            static const char * const day_names[] = { "ВС","ПН", "ВТ", "СР", "ЧТ", "ПТ", "СБ"};
            return day_names[id(sntp_time).now().day_of_week-1];



#-------------------------------------------
# BINARY_SENSOR
#-------------------------------------------            
binary_sensor:
  - id: !extend bin_vl
    on_press:
    - if:
        condition:
          lvgl.page.is_showing: clock_page
        then:
          - light.turn_on: backlight
          - lvgl.page.previous:     

  - id: !extend bin_nl
    on_press:
    - if:
        condition:
          lvgl.page.is_showing: clock_page
        then:
          - light.turn_on: backlight
          - lvgl.page.next:    

  - id: !extend bin_vp
    on_press:
    - if:
        condition:
          lvgl.page.is_showing: clock_page
        then:
          - light.turn_on: backlight
          - lvgl.page.next:    

  - id: !extend bin_np
    on_press:
    - if:
        condition:
          lvgl.page.is_showing: clock_page
        then:
          - light.turn_on: backlight
          - lvgl.page.next:     
            
#-------------------------------------------
# TIME
#-------------------------------------------
time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-3 #Europe/Moscow
    servers: !secret sntp
    on_time_sync:
      - script.execute: time_update_clock  
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update_clock
      - seconds: '*'
        then:
          - lvgl.indicator.update:
              id: seconds_hand
              value: !lambda |-
                return id(sntp_time).now().second;
          - lvgl.indicator.update:
              id: seconds_hand_b
              value: !lambda |-
                return id(sntp_time).now().second;
            
#-------------------------------------------
# LVGL
#-------------------------------------------            
lvgl:
  style_definitions:
    - id: date_style
      text_font: roboto16
      align: center
      text_color: 0x333333
      bg_opa: cover
      radius: 4
      pad_all: 2
  pages:
    - id: clock_page
      widgets:
        - obj: # Clock container
            height: 240
            width: 240
            border_side: none
            bg_color: 0x000000
            scrollbar_mode: "OFF"
            scrollable: false
            radius: 0
            widgets:
              - image:
                  align: CENTER
                  src: clok_image
                  id: im_clock
              - label:
                  styles: date_style
                  id: day_label
                  text: " "
                  x: 50
              - label:
                  id: date_label
                  text: " "
                  styles: date_style
                  y: +40   
              - meter:
                  height: 240
                  width: 240
                  align: center
                  bg_opa: TRANSP
                  text_color: 0xFFFFFF
                  border_width: 0
                  scales:
                    - indicators:
                        - line:
                            id: hour_hand
                            width: 8
                            color: 0x808080
                            r_mod: -80
                      angle_range: 360
                      rotation: 270
                      range_from: 0
                      range_to: 720
                      ticks:
                        count: 0
                    - indicators:
                        - line:
                            id: hour_hand_b
                            width: 8
                            color: 0x808080
                            r_mod: -180
                      angle_range: 360
                      rotation: 90
                      range_from: 0
                      range_to: 720
                      ticks:
                        count: 0
                    - indicators:
                        - line:
                            id: minute_hand
                            width: 4
                            color: 0xB0B0B0
                            r_mod: -45
                      rotation: 270
                      angle_range: 360
                      range_from: 0
                      range_to: 60
                      ticks:
                        count: 0
                    - indicators:
                        - line:
                            id: minute_hand_b
                            width: 4
                            color: 0xB0B0B0
                            r_mod: -180
                      rotation: 90
                      angle_range: 360
                      range_from: 0
                      range_to: 60
                      ticks:
                        count: 0
                    - indicators:
                        - line:
                            id: seconds_hand
                            width: 2
                            color: 0xFF0000
                            r_mod: -30
                      rotation: 270
                      angle_range: 360
                      range_from: 0
                      range_to: 60
                      ticks:
                        count: 0
                    - indicators:
                        - line:
                            id: seconds_hand_b
                            width: 2
                            color: 0xFF0000
                            r_mod: -180
                      rotation: 90
                      angle_range: 360
                      range_from: 0
                      range_to: 60
                      ticks:
                        count: 0
              - led:
                  align: CENTER
                  color: 0xFF0000
                  width: 15
                  height: 15
                  