#############################################################################
#----Страничка посудомойки --------------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/ujin/display/
#packages:
#  dishwasher: !include 
#    file: packages/ujin/display/dishwasher.yaml
#    vars:
#      sensor_dishwasher_percent: sensor.siemens_dishwasher_program_progress
#      sensor_dishwasher_time: sensor.siemens_dishwasher_remaining_program_time 
#      sensor_dishwasher_program_phase: sensor.siemens_dishwasher_program_phase
#      binary_sensor_dishwasher_door: binary_sensor.siemens_dishwasher_door
#      switch_dishwasher_power: switch.siemens_dishwasher_power
#############################################################################



substitutions:
  power:            "\U000F0425" # power
  stop:             "\U000F04DB" # stop
  play:             "\U000F040A" # play
  door:             "\U000F081B" # door-closed  
  water:            "\U000F1505" # water-check-outline
  water_alert:      "\U000F1503" #water-alert-outline
  speedometer:      "\U000F04C5" # speedometer
  volume:           "\U000F0581" # volume-off
  half:             "\U000F1992" # fraction-one-half
  timer:            "\U000F1AE1" # timer-play-outline
  shaker:           "\U000F110F" # shaker-outline
  creation:         "\U000F0674" # creation

    
#-------------------------------------------
# FONT
#-------------------------------------------
font:
  - file: "font/DSEG7ModernMini-Bold.ttf"
    id: SEG24
    glyphs: ${number_characters}
    size: 24
    bpp: 4  

  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: font_dishwasher
    size: 48
    bpp: 4
    glyphs: [
      $power,
      $stop,
      $play,
      $door,
      $water,
      $water_alert,
      $speedometer,
      $volume,
      $half,
      $timer,    
      $shaker,
      $creation
    ]    
    
#-------------------------------------------
# SWITCH
#-------------------------------------------     
switch:
  - platform: homeassistant
    id: sw_dishwasher_power
    entity_id: $switch_dishwasher_power   
    on_turn_on:
      lvgl.widget.update:
        id: l_dishwasher_power
        text_color: 0x00FF00
    on_turn_off:
      lvgl.widget.update:
        id: l_dishwasher_power
        text_color: 0xB6B6B6

#-------------------------------------------
# BINARY_SENSOR
#-------------------------------------------           
binary_sensor:
  - platform: homeassistant
    entity_id: $binary_sensor_dishwasher_door
    id: bin_dishwasher_door
    trigger_on_initial_state: true
    on_press:
      lvgl.widget.update:
        id: l_dishwasher_door
        text_color: 0xFF0000
    on_release:
      lvgl.widget.update:
        id: l_dishwasher_door
        text_color: 0xB6B6B6

#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  - platform: homeassistant
    id:  dishwasher_percent
    entity_id: $sensor_dishwasher_percent
    filters:
      - filter_out: nan
    on_value:
      - lvgl.arc.update:
          id: arc_dishwasher_percent
          value: !lambda |- 
            return x;
      - lvgl.label.update:
          id: label_dishwasher_percent
          text:
            format: "%0.0f %%"
            args: ["x"] 
            
  - platform: homeassistant
    id: ha_dishwasher_time
    entity_id: $sensor_dishwasher_time
    unit_of_measurement: h
    device_class: duration
    filters:
      - filter_out: nan
    on_value:
      then:
        - lvgl.label.update:
            id: l_dishwasher_time
            text: 
              format: "%02.0f:%02.0f"
              args:  ["trunc(id(ha_dishwasher_time).state)", "trunc(fmod(id(ha_dishwasher_time).state , 1.0) * 60.0)"]  
            text_color: black      
#-------------------------------------------
# TEXT_SENSOR
#-------------------------------------------
text_sensor:
  - platform: homeassistant
    id: ha_dishwasher_phase
    entity_id: $sensor_dishwasher_program_phase
    filters:
    #  - to_upper
      - substitute:
        - "PreRinse -> Замачивание" 
        - "MainWash -> Основная мойка" 
        - "FinalRinse -> Ополаскивание"
        - "Drying -> Сушка" 
        - "unavailable -> ВЫКЛ"
        - "None -> "
        
    on_value:
      then:
        - lvgl.label.update:
            id: l_dishwasher_phase
            text: !lambda return x;
              

#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Страничка посудомойки 
    - id: dishwasher_page
      bg_color: 0xdce1e7
      widgets:
        - arc:
            id: arc_dishwasher_percent
            align: CENTER
            arc_width: 20
            width: 240
            height: 240
            min_value: 0
            max_value: 100
            start_angle: 0
            end_angle: 360
            rotation: 90
            value: 100
          #  arc_opa: TRANSP
          #  arc_color: 0x43739e

        - label:
            id: l_dishwasher_phase
            align: CENTER
            text_color: color_dark_gray
            text: "выключено"
            text_font: roboto24
            y: -50
            
        - label:
            id: label_dishwasher_percent
            align: CENTER
            text_color: color_dark_gray
            text: "__%"
            text_font: roboto24
            
        - label:
            id: l_dishwasher_time
            align: CENTER
            text_font: SEG24
            text_color: color_gray
            text: 88:88
            y: 50


        - label:
            id: l_dishwasher_door
            align: CENTER
            text_font: font_dishwasher
            text_color: color_gray
            text: $door
            x: -70
            
        - label:
            id: l_dishwasher_power
            align: CENTER
            text_font: font_dishwasher
            text_color: color_gray
            text: $power
            x: 70

            

