#############################################################################
#----Страничка влажности -------- -------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/ujin/display
#packages:
#  humm: !include  packages/ujin/display/humm.yaml
# 
#############################################################################

#-------------------------------------------
# IMAGE
#-------------------------------------------
image:
  - file: "picture/humm_Logo3.jpg"
    id: humm_image
    resize: 30x30
    type: RGB565 
    transparency: alpha_channel 
    
    
#-------------------------------------------
# BINARY_SENSOR
#-------------------------------------------            
binary_sensor:
  - id: !extend bin_vl
    on_press:
    - if:
        condition:
          lvgl.page.is_showing: humm_page
        then:
          - light.turn_on: backlight
          - lvgl.page.previous:  

  - id: !extend bin_nl
    on_press:
    - if:
        condition:
          lvgl.page.is_showing: humm_page
        then:
          - light.turn_on: backlight
          - lvgl.page.next:    

  - id: !extend bin_vp
    on_press:
    - if:
        condition:
          lvgl.page.is_showing: humm_page
        then:
          - light.turn_on: backlight
          - lvgl.page.next:    

  - id: !extend bin_np
    on_press:
    - if:
        condition:
          lvgl.page.is_showing: humm_page
        then:
          - light.turn_on: backlight
          - lvgl.page.next:  


#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  platform: bme68x_bsec2
  humidity:
    - id: !extend ${id_bme680_h}
      on_value:
        - lvgl.indicator.update:
            id: humm_meter
            value: !lambda |- 
              return x;    

#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Вывод на экран 
    - id: humm_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Оранжевый
        - line:
            points:
              - 85, 85
              - -35, 205
            line_width: 100
            line_color: 0xffa500 
            line_rounded: false 
        - line:
            points:
              - 60, 0
              - 60, 120
            line_width: 120
            line_color: 0xffa500
            line_rounded: false 
            
        # Желтый
        - line:
            points:
              - 165, 95
              - 0, -17
            line_width: 100
            line_color: 0xe7c12c
            line_rounded: false 

        # Зеленый
        - line:
            points:
              - 155, 120
              - 155, 0
            line_width: 70
            line_color:  0x00FF00
            line_rounded: false 
            
        # Салатовый      
        - line:
            points:
              - 154, 140
              - 192, -7
            line_width: 80
            line_color: 0xa6e278 
            line_rounded: false 
        
        # Аквамариновый
        - line:
            points:
              - 155, 140
              - 232, -7 
            line_width: 80
            line_color: 0x78dbe2 
            line_rounded: false 
            
        #Голубой
        - line:
            points:
              - 137, 140
              - 240, 0 #-10
            line_width: 45
            line_color: 0x42aaff
            line_rounded: false 
            
        # Синий
        - line:
            points:
              - 137, 140
              - 255, 35 #-10
            line_width: 45
            line_color: 0x0000ff
            line_rounded: false 

        # Фиолетовый
        - line:
            points:
              - 137, 140
              - 270, 77 #-10
            line_width: 45
            line_color: 0xA63DC2 
            line_rounded: false 
            
        # Темно фиолетовый
        - line:
            points:
              - 180, 110
              - 195, 240
            line_color: 0x6e029c
            line_width: 120
            line_rounded: false
            
         # Белый
        - line:
            points:
              - 52, 292
              - 172, 172
            align: TOP_left
            line_width: 150
            line_color: 0xFFFFFF
            line_rounded: false 

# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
#            border_color: color_blue
#            border_width: 15
            width: 240
            height: 240
            align: center
            scales:
              - ticks: 
                  count: 101
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 10
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
# Индикатор
        - meter:
            width: 180
            height: 180
            align: center
            scales:
              - indicators:
                  - line:
                      id: humm_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
                ticks: 
                  count: 101
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 10
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8

        - image:
            align: CENTER
            src: humm_image
            y: 60
            bg_color: 0xFFFFFF
            bg_image_opa: 100% 
