#############################################################################
#----Страничка VOC ----------------------------------------------------------
#############################################################################
# Add yaml and copy file esphome/packages/ujin/display
#packages:
#  voc: !include file: packages/ujin/display/voc.yaml
# 
#############################################################################

substitutions:
  voc_icon: "\U000F0BAC" # mdi:molecule
font:
  - file: 'font/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
    id: icon_voc
    size: 30
    bpp: 4
    glyphs: [
      $voc_icon
    ]  


#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  - id: !extend bme_bsec2
    breath_voc_equivalent:
      on_value:
        - lvgl.indicator.update:
            id: voc_meter
            value: !lambda |- 
              return x;
#-------------------------------------------
# LVGL
#-------------------------------------------
lvgl:
  pages:
# Вывод на экран 
    - id: voc_page
      #width: 100%
      bg_color: 0x000000
      #opa: cover
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        # Зеленый
        - line:
            points:
              - 85, 85
              - -35, 205
            line_width: 100
            line_color: 0x00ff00
            line_rounded: false 
        # Желтый
        - line:
            points:
              - 45, 110
              - 60, 0
            line_width: 125
            line_color:  0xe7c12c
            line_rounded: false  
        # Оранжевый
        - line:
            points:
              - 85, 55
              - 240, -40
            line_width: 150
            line_color: 0xffa500
            line_rounded: false 
            
        # Красный
        - line:
            points:
              - 165, 148
              - 241, 0 #+5 -5
            line_width: 110
            line_color: 0xF50F34
            line_rounded: false 
        # Красный
        - line:
            points:
              - 180 , 110
              - 195, 240
            line_color: 0xF50F34
            line_width: 120
            line_rounded: false

         # Белый
        - line:
            points:
              - 52, 292
              - 172, 172
            align: TOP_left
            line_width: 150
            line_color: 0xFFFFFF
            line_rounded: false 
# Шкала
        - meter:
            bg_opa: 0%
            opa: 100%
#            border_color: color_white
#            border_width: 15
            width: 240
            height: 240
            align: center
            scales:
              - ticks: 
                  count: 101
                  width: 2
                  length: 10
                  color: 0x000000
                  major:
                    stride: 10
                    width: 3
                    length: 20
                    color: 0x000000
                    label_gap: 10
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 100
# Индикатор
        - meter:
            width: 180
            height: 180
            align: center
            scales:
              - indicators:
                  - line:
                      id: voc_meter
                      width: 4
                      color: 0xFF0000
                      r_mod: -15
                      value: 0
                angle_range: 270
                rotation: 135
                range_from: 0
                range_to: 500
                ticks: 
                  count: 101
                  width: 0
                  length: 0
                  color: 0x000000
                  major:
                    stride: 10
                    width: 0
                    length: 0
                    color: 0x000000
                    label_gap: 8
                    

        - label:
            text: $voc_icon
            text_color: color_black
            text_font: icon_voc
            align: center
            y: 60

