substitutions:
  name: ujin-lume-led
  device_description: ujin-pt-led-din-ch-m2
  
esphome:
  name: "${name}"
  friendly_name: ujin led
  comment: "${device_description}"

esp32:
  board: denky_d4
  flash_size: 8MB
  framework:
    type: esp-idf


#-------------------------------------------
# PSRAM
#------------------------------------------- 
psram:
  mode: quad
  speed: 80MHz
 
#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
# обязательные пакеты
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml
  led_с: !include packages/ujin/led/led_current.yaml 
  led_p: !include packages/ujin/led/led_power.yaml # при использовании необходим led_current.yaml 
  led_pt: !include packages/ujin/led/led_power_total.yaml # при использовании необходим led_current.yaml, led_power.yaml, time.yaml
  time: !include included/time.yaml
# Датчик температуры встроенный NTC
  ntc_i: !include 
    file: packages/ujin/sensor/ntc_internal.yaml
    vars:
      ntc_internal_pin: 35

  #ble: !include # при использовании убрать psram
   # file: packages/ble_adv_controller.yaml
   # file: packages/ujin/ble/ble.yaml
    #file: packages/ujin/ble/ble1.yaml
    #file: packages/ujin/ble/ble2.yaml
   # file: packages/ujin/ble/ble3.yaml
  # file: packages/ujin/ble/ble_adv_proxy.yaml

#-------------------------------------------
# Light
#-------------------------------------------
light:
  - platform: rgbww
    name: "Livingroom Lights"
    red: out_R
    green: out_G
    blue: out_B
    cold_white: out_W1
    warm_white: out_W2
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

  - platform:  status_led
    name: "led green"
    pin: 
      number: 7
      ignore_pin_validation_error: true
    id: light_green

  - platform: binary
    name: "led yellow"
    output: light_yellow

#-------------------------------------------
# OUTPUT
#-------------------------------------------
output:
  - platform: gpio
    pin: 
      number: 8
      ignore_pin_validation_error: true
    id: light_yellow

  - platform: ledc
    id: out_R
    pin: GPIO25
    frequency: 1000 Hz
  - platform: ledc
    id: out_G
    pin: GPIO26
    frequency: 1000 Hz
  - platform: ledc
    id: out_B
    pin: GPIO27
    frequency: 1000 Hz
  - platform: ledc
    id: out_W1
    pin: GPIO13
    frequency: 1000 Hz
  - platform: ledc
    id: out_W2
    pin: GPIO14
    frequency: 1000 Hz

#-------------------------------------------
# BINARY SENSOR
#-------------------------------------------
binary_sensor:
  - platform: gpio
    pin: 
      number: 0
      inverted: yes
    name: "Button"
  - platform: gpio
    pin: 
      number: 4
      inverted: yes
    name: "S1"
  - platform: gpio
    pin: 
      number: 20
      inverted: yes
    name: "S2"

##################################################
  - platform: gpio
    pin: 
      number: 5
    name: "GPIO5"

  - platform: gpio
    pin: 
      number: 12
    name: "GPIO12"

  - platform: gpio
    pin: 
      number: 15
    name: "GPIO15"

  - platform: gpio
    pin: 
      number: 19
    name: "GPIO19"

  - platform: gpio
    pin: 
      number: 22
    name: "GPIO22"
    
