#-------------------------------------------
# Add yaml 
#packages:
#  but: !include 
#    file: packages/ujin/button/button_aqua.yaml
#    vars:
#      one_butt: GPIO15
#      two_butt: GPIO2
#      touch_threshold_right: 1000
#      touch_threshold_left: 1000
#      touch_threshold: 1000 #1150
#      delta_threshold: 5
#      setup_threshold: false #true
# and copy file esphome/packages/ujin/button

 
#-------------------------------------------
# TOUCH
#-------------------------------------------
esp32_touch:
  setup_mode: $setup_threshold


#-------------------------------------------
# BINARY SENSOR
#-------------------------------------------
binary_sensor:
  - platform: esp32_touch
    name: "левая кнопка"
    id: left_touch
    pin: $one_butt
    icon: mdi:gesture-tap-button
    threshold: $touch_threshold_left
    on_click: 
      then:
        - switch.toggle: valve
        - if:
            condition:
              switch.is_on: sound
            then:
              - rtttl.play: 'short:d=20,o=5,b=100:e6'  


  - platform: esp32_touch
    name: "правая кнопка"
    id: right_touch
    pin: $two_butt
    icon: mdi:gesture-tap-button
    threshold: $touch_threshold_right
    on_click: 
      then:
        - switch.toggle: valve
        - if:
            condition:
              switch.is_on: sound
            then:
              - rtttl.play: 'short:d=20,o=5,b=100:e6'           
#-------------------------------------------
# SELECT
#-------------------------------------------
select:
  - platform: template
    name: "Чувствительность кнопок"
    id: sensitivity_of_touch_id
    entity_category: config
    icon: mdi:gesture-tap-hold
    options:
      - "Низкая"              
      - "Средняя"             
      - "Высокая"          
    initial_option: "Средняя"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            switch(i) {
              case 0: 
                id(right_touch).set_threshold ($touch_threshold_right - $delta_threshold); 
                id(left_touch).set_threshold ($touch_threshold_left - $delta_threshold); 
                break;
              case 1:  
                id(right_touch).set_threshold ($touch_threshold_right); 
                id(left_touch).set_threshold ($touch_threshold_left); 
                break;
              case 2:  
                id(right_touch).set_threshold ($touch_threshold_right + $delta_threshold); 
                id(left_touch).set_threshold ($touch_threshold_left + $delta_threshold); 
                break;
            }
              
              
              
              