# https://stuvel.eu/post/2022-06-05-esphome-touch-dimmer/

#-------------------------------------------
# Add yaml 
#packages:
#  but: !include 
#    file: packages/ujin/button/button.yaml
#    vars:
#      one_butt: GPIO15
#      two_butt: GPIO2
#      touch_threshold_1: 1000 #1150
#      touch_threshold_2: 1000 #1150
#      delta_threshold: 5
#      setup_threshold: false #true
# and copy file esphome/packages/ujin/button

esphome:
  includes:
    - packages/ujin/touch-dimming.h 
  on_boot:
    - priority: 500
      then:
        - lambda: new TouchDimmer("dimm1", light_dimmer1, left_touch, binary_dimm1);
        - lambda: new TouchDimmer("dimm2", light_dimmer2, right_touch, binary_dimm2);   
#-------------------------------------------
# TOUCH
#-------------------------------------------
esp32_touch:
  setup_mode: $setup_threshold


#-------------------------------------------
# BINARY SENSOR
#-------------------------------------------
binary_sensor:
  - platform: esp32_touch
    name: "левая кнопка"
    id: left_touch
    pin: $one_butt
    icon: mdi:gesture-tap-button
    threshold: $touch_threshold_1

  - platform: esp32_touch
    name: "правая кнопка"
    id: right_touch
    pin: $two_butt
    icon: mdi:gesture-tap-button
    threshold: $touch_threshold_2


  - platform: template
    id: binary_dimm1

  - platform: template
    id: binary_dimm2              
#-------------------------------------------
# SELECT
#-------------------------------------------
select:
  - platform: template
    name: "Чувствительность кнопок"
    id: sensitivity_of_touch_id
    entity_category: config
    icon: mdi:gesture-tap-hold
    options:
      - "Низкая"              
      - "Средняя"             
      - "Высокая"          
    initial_option: "Средняя"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            switch(i) {
              case 0: 
                id(right_touch).set_threshold ($touch_threshold_1 - $delta_threshold); 
                id(left_touch).set_threshold ($touch_threshold_2 - $delta_threshold); 
                break;
              case 1:  
                id(right_touch).set_threshold ($touch_threshold_1); 
                id(left_touch).set_threshold ($touch_threshold_2); 
                break;
              case 2:  
                id(right_touch).set_threshold ($touch_threshold_1 + $delta_threshold); 
                id(left_touch).set_threshold ($touch_threshold_2 + $delta_threshold); 
                break;
            }
              
              
              
              