#-------------------------------------------
# Add yaml 
#packages:
#  but: !include 
#    file: packages/ujin/button/button_uart.yaml
#    vars:
#      one_butt: GPIO2
#      two_butt: GPIO4
#      touch_threshold: 1000 #1150
#      delta_threshold: 5
#      setup_threshold: false #true
# and copy file esphome/packages/ujin/button
esphome:
  includes:
    - packages/ujin/touch-dimming.h 
  on_boot:
    - priority: 500
      then:
        - lambda: new TouchDimmer("dimm1", light_dimmer1, left_touch, binary_dimm1);
        - lambda: new TouchDimmer("dimm2", light_dimmer2, right_touch, binary_dimm2);   

#-------------------------------------------
# SCRIPT
#-------------------------------------------
script:
  - id: my_script
    then:
      - delay: 1s
#-------------------------------------------
# TOUCH
#-------------------------------------------
esp32_touch:
  setup_mode: $setup_threshold


#-------------------------------------------
# BINARY SENSOR
#-------------------------------------------
binary_sensor:
  - platform: esp32_touch
    name: "${name} левая кнопка"
    id: left_touch
    pin: $one_butt
    icon: mdi:gesture-tap-button
    threshold: $touch_threshold
    on_click:
      then:
        - if:
            condition:
              switch.is_on: sound
            then:
              - lambda: |-
                  std::vector<uint8_t> message = {0xC8, 0x07, 0x0B, 0x02, 0x00, 0xFA, 0x3C};          
                  id(uart_0).write_array(message.data(), message.size());
            
  - platform: esp32_touch
    name: "${name} правая кнопка"
    id: right_touch
    pin: $two_butt
    icon: mdi:gesture-tap-button
    threshold: $touch_threshold
    on_click:
      then:
        - if:
            condition:
              switch.is_on: sound
            then:
              - lambda: |-
                  std::vector<uint8_t> message = {0xC8, 0x07, 0x0B, 0x02, 0x00, 0xFA, 0x3C};          
                  id(uart_0).write_array(message.data(), message.size());

  - platform: template
    id: binary_dimm1

  - platform: template
    id: binary_dimm2              
#-------------------------------------------
# SELECT
#-------------------------------------------
select:
  - platform: template
    name: "Чувствительность кнопок"
    id: sensitivity_of_touch_id
    entity_category: config
    icon: mdi:gesture-tap-hold
    options:
      - "Низкая"              
      - "Средняя"             
      - "Высокая"          
    initial_option: "Средняя"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            switch(i) {
              case 0: 
                id(right_touch).set_threshold ($touch_threshold - $delta_threshold); 
                id(left_touch).set_threshold ($touch_threshold - $delta_threshold); 
                break;
              case 1:  
                id(right_touch).set_threshold ($touch_threshold); 
                id(left_touch).set_threshold ($touch_threshold); 
                break;
              case 2:  
                id(right_touch).set_threshold ($touch_threshold + $delta_threshold); 
                id(left_touch).set_threshold ($touch_threshold + $delta_threshold); 
                break;
            }
              
              
              
              
