esphome:
  on_boot:
    priority: -100
    then:
    - esp32_ble_tracker.start_scan:
  on_shutdown: 
    priority: 800
    then:
      - esp32_ble_tracker.stop_scan:

#bluetooth_proxy:
#  active: true
  
time:
  - platform: sntp
    id: sntp_time
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    timezone: Europe/Moscow
    on_time:
      - seconds: 0
        minutes: 0/5
        then:
          - esp32_ble_tracker.start_scan:
      - seconds: 30
        minutes: 0/5
        then:
          - esp32_ble_tracker.stop_scan:
          
esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    continuous: false
    duration: 18min
