substitutions:
  name: lume-co2
  device_description: Lume Luxe wifi/BLE/IR/CO2
  light_1_device: light.kithen1
  light_2_device: light.gyverlamp
  sda_i2c: GPIO21
  scl_i2c: GPIO22

esphome:
  name: "${name}"
  comment: "${device_description}"
  on_boot:
    - priority: 600
      then:
        - lambda:   
            pinMode(14, OUTPUT); 
            digitalWrite(14, LOW); 

    - priority: 250
      then:    
        - uart.write: !lambda
            return {0xC8, 0x29, 0x66, 0x24, 0xF0, 0xFF, 0xAC, 0x0D, 0x4C, 0x1D, 0x32, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x00, 0xC5, 0xFF, 0xCA, 0x08, 0x4C, 0x1D, 0x32, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x00, 0xC4, 0xFF, 0xF4, 0x01, 0x00, 0x00, 0x34, 0x12, 0x1D};
                  #   |     |     |     |     ↑     |     ↑     ↑     ↑     ↑     |     |     |     |     ↑     ↑     |     |     ↑    |      ↑    ↑     ↑     ↑      |     |     |     |     ↑     ↑     |     |     ↑     |     |     |     |     |     |     |     |
                  #   |     |     |     |     ↑     |     ↑     ↑     ↑     ↑     |     |     |     |    Таймер 1     |     |     ↑    |      ↑    ↑     ↑     ↑      |     |     |     |    Таймер 2     |     |     ↑     |     |     |     |     |     |     |     |
                  #   |     |     |     |     ↑     |     ↑     ↑  граница мин 1  |     |     |     |     |     |     |     |     ↑    |      ↑    ↑    граница мин 2 |     |     |     |     |     |     |     |     ↑     |     |     |     |     |     |     |     |
                  #   |     |     |     |     ↑     |  граница мax 1              |     |     |     |     |     |     |     |     ↑    |     граница мax 2            |     |     |     |     |     |     |     |     ↑     |     |     |     |     |     |     |     |
                  #   |     |     |     |  Питание по фазе и нулю - F1, по фазе  - F0   |     |     |     |     |     |     |  Диммирование 1 канал C4-OFF C5-ON      |     |     |     |     |     |     |     | Диммирование 2 канал C4-OFF C5-ON

api:
  reboot_timeout: 0s     
  
esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: arduino
#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: quad
  speed: 120MHz

logger:
  baud_rate: 0

uart:
  - id: uart_0
    baud_rate: 115200
    rx_pin: 3
    tx_pin: 1
    data_bits: 8
    stop_bits: 1

#-------------------------------------------
# I2c
#-------------------------------------------
i2c:
  sda: $sda_i2c
  scl: $scl_i2c

#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
# обязательные пакеты
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml

  dimm_uart: !include 
    file: packages/ujin/dimmer/dimm_uart.yaml
    vars:
      type_light1: monochromatic # binary
      type_light2: monochromatic # binary

# Сенсорные кнопки
  but: !include 
    file: packages/ujin/button/button_uart.yaml
    vars:
      one_butt: GPIO2
      two_butt: GPIO4
      touch_threshold: 1000 #1150
      delta_threshold: 5
      setup_threshold: false #true
      
# не обязательные пакеты
 # time: !include included/time.yaml

# Температура ESP32
  esp32_temp: !include packages/ujin/sensor/esp32_temp.yaml

# Датчик холла
  esp32_hall: !include packages/ujin/sensor/esp32_hall.yaml

# ИК приемник на версии платы 2.4 не работает (срабатывает сторожевой таймер)!!!!
#  ir_receiver: !include 
#    file: packages/ujin/sensor/ir_receiver.yaml
#    vars:
#      pin_ir_receiver: GPIO33

# ИК передатчик
  ir_transmitter: !include 
    file: packages/ujin/sensor/ir_transmitter.yaml
    vars:
      pin_ir_transmitter: GPIO25

# Датчик освещености
  bh1750: !include
    file: packages/ujin/sensor/bh1750.yaml
    vars:
     id_bh: i_lume

# Датчик температуры и влажности 
 # sht3x: !include 
  #  file: packages/ujin/sensor/sht3x.yaml
  # vars:
   #   id_sht3x_t: sht3x_t
   #   id_sht3x_h: sht3x_h

# Датчик CO2
#  ccs811: !include 
#    file: packages/ujin/sensor/ccs811.yaml
#    vars:
#      id_ccs811_t: sht3x_t
#      id_ccs811_h: sht3x_h
#      id_ccs811_eco2: ccs811_eco2
#      id_ccs811_tvoc: ccs811_tvoc

# Датчик температуры, влажности, CO2, давления, VOC, качества воздуха 
  bme680_bsec: !include 
    file: packages/ujin/sensor/bme680_bsec2.yaml
    vars:
      id_bme680_t: bme680_t
      id_bme680_h: bme680_h
      id_bme680_p: bme680_p
      id_bme680_iaq: bme680_iaq
      id_bme680_co2: bme680_co2
      id_bme680_voc: bme680_voc
      model_bme: bme688
      address_bme680: 0x76

# Подсведка кнопок
  led: !include 
    file: packages/ujin/led/led_lume.yaml
    vars:
      led_lume_pin: GPIO26
      led_lume: 5

# Входы
#  1in: !include 
#    file: packages/ujin/1in.yaml
#    vars:
#      one_pin: GPIO32
# Входы
  2in: !include 
    file: packages/ujin/2in_uart.yaml


# Шумомер
  noise: !include 
    file: packages/ujin/sensor/noise_PDM_05.2025.yaml
    vars:
      noise_ws: GPIO13
      noise_din: GPIO15

# Датчик движения
  pir: !include 
    file: packages/ujin/sensor/pir.yaml
    vars:
      pir_pin: GPIO34
      pir_addres: 0x28

#-------------------------------------------
# SWITCH
#-------------------------------------------
switch:
  - platform: template
    name: "Звук нажатие клавиш"
    optimistic: True
    id: sound
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:volume-off

# В процесе написания
#sensor:
 # - platform: hts221
  #  temperature:
  #    name: "Living Room Temperature"
   # humidity:
   #   name: "Living Room Humidity"
   # update_interval: 60s
