esphome:
  name: ujin-pulse
  friendly_name: ujin-pulse
 
esp32:
  board: denky_d4
  flash_size: 8MB
  framework:
    type: esp-idf

#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: quad
  speed: 80MHz
#-------------------------------------------
# EXTERNAL COMPONENTS
#-------------------------------------------
external_components:
  - source: github://ananyevgv/esphome-components/
    refresh: 0s

#-------------------------------------------
# I2c
#-------------------------------------------
i2c:
  sda:
    number: GPIO13
  scl: 
    number: GPIO15
  scan: true
  id: bus_a
  frequency:
    10kHz

output:
  - platform: ledc
    pin: GPIO12
    id: rtttl_out
# Create the MCP453X output
  - platform: mcp453x
    id: pir_output
    mcp453x_id: my_mcp453x  
    
cap1293:
  id: cap1293_component
  address: 0x12
  reset_pin: GPIO20
  touch_threshold: 0x20
  allow_multiple_touches: true
#-------------------------------------------
# MCP453X
#-------------------------------------------
mcp453x:
  id: my_mcp453x
  address: 0x2F


packages:
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml
# Датчик температуры, влажности, CO2, давления, VOC, качества воздуха 
  bme680_bsec: !include 
    file: packages/ujin/sensor/bme680_bsec2.yaml
    vars:
      id_bme680_t: bme680_t
      id_bme680_h: bme680_h
      id_bme680_p: bme680_p
      id_bme680_iaq: bme680_iaq
      id_bme680_co2: bme680_co2
      id_bme680_voc: bme680_voc
      model_bme: bme688
      address_bme680: 0x76
      t_offset: 0

#-------------------------------------------
# I2S
#-------------------------------------------
i2s_audio:
  i2s_lrclk_pin: 19
  i2s_bclk_pin: 22

#-------------------------------------------
# MICROPHONE
#-------------------------------------------
microphone:
  - platform: i2s_audio
    id: external_mic
    adc_type: external
    i2s_din_pin: 21
    channel: left
    pdm: true
    bits_per_sample: 16bit
    bits_per_channel: 8bit
    sample_rate: 16000
    




# Enable Home Assistant API
api:

  actions:
    - action: rtttl_play
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
  reboot_timeout: 0s    
  


#-------------------------------------------
# RTTTL
#-------------------------------------------
rtttl:
  output: rtttl_out
  gain: 60%







light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO5
    num_leds: 35
  #  rmt_channel: 1
    chipset: WS2812
    id: led_ww
#    name: "Светодиоды на мультисенсоре"



#-------------------------------------------
# BINARY SENSOR
#-------------------------------------------
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO2
    id: pir_id
    name: pir  
    icon: mdi:motion-sensor


  - platform: analog_threshold
    name: "Датчик шума"
    id: noise
    threshold: -20
    sensor_id: Leq_id
    device_class: sound
    icon: mdi:speaker-wireless



logger:
  level: DEBUG  # для детальных логов

select:
  - platform: template
    name: "Чувствительность датчика движения"
    entity_category: config
    icon: mdi:motion-sensor
    options:
     - "Очень высокая"      
     - "Высокая"
     - "Средняя"
     - "Низкая"
     - "Очень низкая"     
    initial_option: "Очень высокая"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            switch(i) {
              case 0: id(pir_output).set_level(0); break;
              case 1: id(pir_output).set_level(0.25); break;
              case 2: id(pir_output).set_level(0.50); break;
              case 3: id(pir_output).set_level(0.75); break;
              case 4: id(pir_output).set_level(1.0); break;
            }

sensor:
  - platform: adc
    pin: 37
    id: adc_37    
#    name: "adc_37"
    update_interval: 10s
    attenuation: auto

      
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 5 kOhm
    name: NTC Temperature
    icon: mdi:thermometer
    id: NTC_Temperature

  # Example source sensors:
  - platform: resistance
    id: resistance_sensor
    sensor: adc_37
    configuration: UPSTREAM
    resistor: 5 kOhm
#    name: Resistance Sensor  

  - platform: ltr_als_ps
    address: 0x29
    id: Ambient_light_id
    update_interval: 1 s
    type: ALS_PS  
    ambient_light: "Освещенность"
    ps_cooldown: 5 s

  - platform: sound_level
    passive: false
    peak:
      name: "шум пиковый уровень"
      id: Leq_id
      icon: mdi:waveform
      filters:
        - delta: 5

script:
  - id: led_off_id
    mode: restart
    then: 
      - light.addressable_set:
           id: led_ww
           range_from: 0
           range_to: 34
           red: 0%
           green: 0%
           blue: 0%
           color_brightness: 100% 

  - id: buzzer_id
    mode: restart
    then:
      - rtttl.play: 'short:d=20,o=5,b=100:e6' 
      - delay: 500ms
      - rtttl.play: 'short:d=20,o=5,b=100:e6' 
      - delay: 500ms
      - script.execute: buzzer_id  # Вызовите скрипт снова 

      

switch:
  - platform: template
    name: "Звук"
    id: sound_id
    icon: mdi:light-switch-off
    optimistic: True
#    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
          - script.execute: buzzer_id           
    on_turn_off:
          - script.stop: buzzer_id

  - platform: template
    name: "Дисплей"
    id: display_id
    icon: mdi:light-switch-off
    optimistic: True
#    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    
display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: led_ww  # Указываем ID светодиодной матрицы
    width: 7  # Ширина (количество столбцов)
    height: 5  # Высота (количество строк)
    rotation: 0°  # Поворот (0°, 90°, 180°, 270°)
    update_interval: 16ms  # Частота обновления
    # Кастомный pixel_mapper (Pulse таблица 5x7)
    pixel_mapper: |-
      static const uint8_t led_map[5][7] = {
        {21, 20, 19,  0, 18, 17, 16},  // y=0
        {22, 23, 24,  1, 13, 14, 15},  // y=1
        {27, 26, 25,  2, 12, 11, 10},  // y=2
        {28, 29, 30, 34,  7,  8,  9},  // y=3
        { 3, 31, 32, 33,  6,  5,  4}   // y=4
      };
      return led_map[y][x];          
    lambda: |-
          Color red = Color(0xFF0000);
          Color green = Color(0x00FF00);
          Color blue = Color(0x0000FF);
          Color white = Color(0x000000);              
          if (id(display_id).state) {
            it.rectangle(0, 0, 7, 5, red);
            it.rectangle(1, 1, 5, 3, green);
            it.rectangle(2, 2, 3, 1, blue);
          }  
          else {
            it.rectangle(0, 0, 7, 5, white);
         
          }
