esphome:
  name: ujin-pulse
  friendly_name: ujin-pulse
  on_boot:
    - rtttl.play: 'short:d=20,o=5,b=100:e6' 

esp32:
  board: denky_d4
  flash_size: 8MB
  framework:
    type: esp-idf

#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: quad
  speed: 80MHz

#-------------------------------------------
# I2c
#-------------------------------------------
i2c:
  sda: GPIO13
  scl: GPIO15

#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml

# Zigbee шлюз      
 # zigbee: !include 
 #   file: packages/ujin/zigbee.yaml
  #  vars:
  #    TX_Z: GPIO8
   #   RX_Z: GPIO7 

# Датчики  
# Датчик освещености
#  ltr: !include 
#    file: packages/ujin/sensor/LTR329.yaml

# Датчик температуры встроенный NTC
  ntc_i: !include 
    file: packages/ujin/sensor/ntc_internal.yaml
    vars:
      ntc_internal_pin: 37

# Датчик температуры, влажности, CO2, давления, VOC, качества воздуха 
#  bme680_bsec: !include 
#    file: packages/ujin/sensor/bme680_bsec2.yaml
 #   vars:
  #    id_bme680_t: bme680_t
  #    id_bme680_h: bme680_h
   #   id_bme680_p: bme680_p
   #   id_bme680_iaq: bme680_iaq
   #   id_bme680_co2: bme680_co2
   #   id_bme680_voc: bme680_voc
   #   model_bme: bme688
   #   address_bme680: 0x76
   #   t_offset: 0

#  noise: !include 
#    file: packages/ujin/sensor/noise_ekf.yaml
#    vars:
#      noise_bck: GPIO22
#      noise_ws: GPIO19
#      noise_din: GPIO21
# and copy file esphome/ujin/sensor/

  pir: !include 
    file: packages/ujin/sensor/pir_ekf.yaml
    vars:
      pir_pin: GPIO2
      pir_addres: 0x2F
# and copy file esphome/packages/ujin/sensor/
    
output:
  - platform: ledc
    pin: GPIO12
    id: rtttl_out
#-------------------------------------------
# RTTTL
#-------------------------------------------
rtttl:
  output: rtttl_out
  gain: 60%


light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO5
    num_leds: 35
    chipset: WS2812
    id: led_ww
#    name: "Светодиоды на мультисенсоре"


switch:
  - platform: template
    name: "Звук"
    id: sound_id
    icon: mdi:light-switch-off
    optimistic: True
    entity_category: config


  - platform: template
    name: "Дисплей"
    id: display_id
    icon: mdi:light-switch-off
    optimistic: True
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    
display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: led_ww  # Указываем ID светодиодной матрицы
    width: 7  # Ширина (количество столбцов)
    height: 5  # Высота (количество строк)
    rotation: 0°  # Поворот (0°, 90°, 180°, 270°)
    update_interval: 16ms  # Частота обновления
    # Кастомный pixel_mapper (Pulse таблица 5x7)
    pixel_mapper: |-
      static const uint8_t led_map[5][7] = {
        {21, 20, 19,  0, 18, 17, 16},  // y=0
        {22, 23, 24,  1, 13, 14, 15},  // y=1
        {27, 26, 25,  2, 12, 11, 10},  // y=2
        {28, 29, 30, 34,  7,  8,  9},  // y=3
        { 3, 31, 32, 33,  6,  5,  4}   // y=4
      };
      return led_map[y][x];          
    lambda: |-
          Color red = Color(0xFF0000);
          Color green = Color(0x00FF00);
          Color blue = Color(0x0000FF);
          Color white = Color(0x000000);              
          if (id(display_id).state) {
            it.rectangle(0, 0, 7, 5, red);
            it.rectangle(1, 1, 5, 3, green);
            it.rectangle(2, 2, 3, 1, blue);
          }  
          else {
            it.rectangle(0, 0, 7, 5, white);
         
          }