#-------------------------------------------
# SENSOR ESP32 TEMPERATURE
#-------------------------------------------
sensor:
  - platform: internal_temperature
    name: "ESP32 T"
    icon: mdi:cpu-32-bit