#-------------------------------------------
# Add yaml and copy file esphome/packages/ujin/sensor/
#packages:
#  sht3x: !include 
#    file: packages/ujin/sensor/sht3x.yaml
#    vars:
#      id_sht3x_t: sht3x_t
#      id_sht3x_h: sht3x_h
#-------------------------------------------

#-------------------------------------------
# SENSOR SHT3X
#-------------------------------------------
sensor:
  - platform: sht3xd
    temperature:
      name: "temperature"
      id: ${id_sht3x_t}
      icon: mdi:thermometer
      filters:
        - median:
        - delta: 0.2
    humidity:
      name: "humidity"
      id: ${id_sht3x_h}
      icon: mdi:water-percent
      filters:
      - delta: 1
    update_interval: 60s
    address: 0x44
 
  - platform: absolute_humidity
    name: "Absolute Humidity"
    temperature: ${id_sht3x_t}
    humidity: ${id_sht3x_h}   
    icon: mdi:water-outline