substitutions:
  name: ujin-aqua
  device_description: ujin-aqua
  beeper_ledc: GPIO25

esphome:
  name: "${name}"
  comment: "${device_description}"
  platformio_options:
    board_upload.maximum_size: 7864320

api:
  reboot_timeout: 0s     
  
esp32:
  board: denky_d4
  flash_size: 8MB
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1" 
    
#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: quad
  speed: 80MHz

#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
# обязательные пакеты
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml

# Сенсорные кнопки
  but: !include 
    file: packages/ujin/button/button_aqua.yaml
    vars:
      one_butt: GPIO15
      two_butt: GPIO2
      touch_threshold_right: 1000
      touch_threshold_left: 1000
      #touch_threshold: 1000 # 1150 
      delta_threshold: 5
      setup_threshold: false #true

# не обязательные пакеты
# BLE
  ble: !include 
  #  file: packages/ujin/ble/ble.yaml
  #  file: packages/ujin/ble/ble1.yaml
    file: packages/ujin/ble/ble2.yaml

  leak-0: !include 
    file: packages/ujin/sensor/leak-ble.yaml
    vars:
      leak_mac: 01:00:5E:00:1D:88
      leak_name: basement
      
  leak-1: !include 
    file: packages/ujin/sensor/leak-ble.yaml
    vars:
      leak_mac: 01:00:5E:00:1D:89
      leak_name: bedrum  

  leak-2: !include 
    file: packages/ujin/sensor/leak-ble.yaml
    vars:
      leak_mac: 01:00:5E:00:1D:88
      leak_name: holl 

# Время NTP
 # time: !include included/time.yaml

# Температура ESP32
  esp32_temp: !include packages/ujin/sensor/esp32_temp.yaml
  
# Captive portal
#  cap: !include 
#    file: packages/ujin/captive.yaml
#    vars:
#      ssid_captive: "Lume"
#      pass_captive: "12345678"

  valve: !include 
    file: packages/ujin/valve/valve.yaml
    vars:
      pin_close: GPIO19
      pin_open: GPIO3
      pin_leak: GPIO33


# Подсведка кнопок
  led: !include 
    file: packages/ujin/led/led_aqua.yaml
    vars:
      led_lume_pin: GPIO26
      led_lume: 5

#-------------------------------------------
# OUTPUT
#-------------------------------------------      
output:
  - platform: ledc
    pin: $beeper_ledc
    id: rtttl_out

#-------------------------------------------
# RTTTL
#-------------------------------------------
rtttl:
  output: rtttl_out
  gain: 60%

#-------------------------------------------
# SWITCH
#-------------------------------------------
switch:
  - platform: template
    name: "Звук нажатие клавиш"
    optimistic: True
    id: sound
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:volume-off
